# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import type_pb2 as common_dot_type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='global/config.proto',
  package='global',
  syntax='proto3',
  serialized_options=_b('\n\031frame.socket.global.proto\370\001\001'),
  serialized_pb=_b('\n\x13global/config.proto\x12\x06global\x1a\x11\x63ommon/type.proto\"f\n\nServerInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12!\n\x04type\x18\x04 \x01(\x0e\x32\x13.common.Server_Type\x12\x0f\n\x07subType\x18\x05 \x01(\x05\"\x14\n\x12GetServerListA2C_R\"6\n\x12GetServerListC2A_S\x12 \n\x04info\x18\x01 \x03(\x0b\x32\x12.global.ServerInfoB\x1e\n\x19\x66rame.socket.global.proto\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[common_dot_type__pb2.DESCRIPTOR,])




_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='global.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='global.ServerInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='global.ServerInfo.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='global.ServerInfo.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='global.ServerInfo.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subType', full_name='global.ServerInfo.subType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=152,
)


_GETSERVERLISTA2C_R = _descriptor.Descriptor(
  name='GetServerListA2C_R',
  full_name='global.GetServerListA2C_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=174,
)


_GETSERVERLISTC2A_S = _descriptor.Descriptor(
  name='GetServerListC2A_S',
  full_name='global.GetServerListC2A_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='global.GetServerListC2A_S.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=230,
)

_SERVERINFO.fields_by_name['type'].enum_type = common_dot_type__pb2._SERVER_TYPE
_GETSERVERLISTC2A_S.fields_by_name['info'].message_type = _SERVERINFO
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['GetServerListA2C_R'] = _GETSERVERLISTA2C_R
DESCRIPTOR.message_types_by_name['GetServerListC2A_S'] = _GETSERVERLISTC2A_S
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINFO,
  __module__ = 'global.config_pb2'
  # @@protoc_insertion_point(class_scope:global.ServerInfo)
  ))
_sym_db.RegisterMessage(ServerInfo)

GetServerListA2C_R = _reflection.GeneratedProtocolMessageType('GetServerListA2C_R', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVERLISTA2C_R,
  __module__ = 'global.config_pb2'
  # @@protoc_insertion_point(class_scope:global.GetServerListA2C_R)
  ))
_sym_db.RegisterMessage(GetServerListA2C_R)

GetServerListC2A_S = _reflection.GeneratedProtocolMessageType('GetServerListC2A_S', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVERLISTC2A_S,
  __module__ = 'global.config_pb2'
  # @@protoc_insertion_point(class_scope:global.GetServerListC2A_S)
  ))
_sym_db.RegisterMessage(GetServerListC2A_S)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
