# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gate/gate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import type_pb2 as common_dot_type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gate/gate.proto',
  package='gate',
  syntax='proto3',
  serialized_options=_b('\n\027frame.socket.gate.proto\370\001\001'),
  serialized_pb=_b('\n\x0fgate/gate.proto\x12\x04gate\x1a\x11\x63ommon/type.proto\"\'\n\rRegisterA2G_R\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02no\x18\x02 \x01(\x05\"e\n\x12RegisterDebugA2G_R\x12\n\n\x02id\x18\x01 \x01(\x05\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.common.Server_Type\x12\x10\n\x08sub_type\x18\x03 \x01(\x05\x12\x0e\n\x06siteId\x18\x04 \x01(\x05\"\x0f\n\rRegisterG2A_S\"\'\n\x16RegisterBroadcastA2G_R\x12\r\n\x05group\x18\x01 \x01(\t\"\x18\n\x16RegisterBroadcastG2A_SB\x1c\n\x17\x66rame.socket.gate.proto\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[common_dot_type__pb2.DESCRIPTOR,])




_REGISTERA2G_R = _descriptor.Descriptor(
  name='RegisterA2G_R',
  full_name='gate.RegisterA2G_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gate.RegisterA2G_R.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no', full_name='gate.RegisterA2G_R.no', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=83,
)


_REGISTERDEBUGA2G_R = _descriptor.Descriptor(
  name='RegisterDebugA2G_R',
  full_name='gate.RegisterDebugA2G_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gate.RegisterDebugA2G_R.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='gate.RegisterDebugA2G_R.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='gate.RegisterDebugA2G_R.sub_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='gate.RegisterDebugA2G_R.siteId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=186,
)


_REGISTERG2A_S = _descriptor.Descriptor(
  name='RegisterG2A_S',
  full_name='gate.RegisterG2A_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=203,
)


_REGISTERBROADCASTA2G_R = _descriptor.Descriptor(
  name='RegisterBroadcastA2G_R',
  full_name='gate.RegisterBroadcastA2G_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='gate.RegisterBroadcastA2G_R.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=244,
)


_REGISTERBROADCASTG2A_S = _descriptor.Descriptor(
  name='RegisterBroadcastG2A_S',
  full_name='gate.RegisterBroadcastG2A_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=270,
)

_REGISTERDEBUGA2G_R.fields_by_name['type'].enum_type = common_dot_type__pb2._SERVER_TYPE
DESCRIPTOR.message_types_by_name['RegisterA2G_R'] = _REGISTERA2G_R
DESCRIPTOR.message_types_by_name['RegisterDebugA2G_R'] = _REGISTERDEBUGA2G_R
DESCRIPTOR.message_types_by_name['RegisterG2A_S'] = _REGISTERG2A_S
DESCRIPTOR.message_types_by_name['RegisterBroadcastA2G_R'] = _REGISTERBROADCASTA2G_R
DESCRIPTOR.message_types_by_name['RegisterBroadcastG2A_S'] = _REGISTERBROADCASTG2A_S
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterA2G_R = _reflection.GeneratedProtocolMessageType('RegisterA2G_R', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERA2G_R,
  __module__ = 'gate.gate_pb2'
  # @@protoc_insertion_point(class_scope:gate.RegisterA2G_R)
  ))
_sym_db.RegisterMessage(RegisterA2G_R)

RegisterDebugA2G_R = _reflection.GeneratedProtocolMessageType('RegisterDebugA2G_R', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERDEBUGA2G_R,
  __module__ = 'gate.gate_pb2'
  # @@protoc_insertion_point(class_scope:gate.RegisterDebugA2G_R)
  ))
_sym_db.RegisterMessage(RegisterDebugA2G_R)

RegisterG2A_S = _reflection.GeneratedProtocolMessageType('RegisterG2A_S', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERG2A_S,
  __module__ = 'gate.gate_pb2'
  # @@protoc_insertion_point(class_scope:gate.RegisterG2A_S)
  ))
_sym_db.RegisterMessage(RegisterG2A_S)

RegisterBroadcastA2G_R = _reflection.GeneratedProtocolMessageType('RegisterBroadcastA2G_R', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERBROADCASTA2G_R,
  __module__ = 'gate.gate_pb2'
  # @@protoc_insertion_point(class_scope:gate.RegisterBroadcastA2G_R)
  ))
_sym_db.RegisterMessage(RegisterBroadcastA2G_R)

RegisterBroadcastG2A_S = _reflection.GeneratedProtocolMessageType('RegisterBroadcastG2A_S', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERBROADCASTG2A_S,
  __module__ = 'gate.gate_pb2'
  # @@protoc_insertion_point(class_scope:gate.RegisterBroadcastG2A_S)
  ))
_sym_db.RegisterMessage(RegisterBroadcastG2A_S)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
