# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gate/login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gate/login.proto',
  package='gate',
  syntax='proto3',
  serialized_options=_b('\n\027frame.socket.gate.proto\370\001\001'),
  serialized_pb=_b('\n\x10gate/login.proto\x12\x04gate\"8\n\x08LoginReq\x12\x0e\n\x06siteId\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0c\n\x04\x61uth\x18\x03 \x01(\t\"\r\n\x0bLoginG2LY_R\"\x14\n\x12LoginFailureLY2G_S\"M\n\x0cReconnectReq\x12\x0e\n\x06siteId\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07\x65nterId\x18\x03 \x01(\x05\x12\x0c\n\x04\x61uth\x18\x04 \x01(\t\"\x1c\n\x0cReconnectRes\x12\x0c\n\x04\x61uth\x18\x01 \x01(\t\"#\n\x11LoginGameQueryReq\x12\x0e\n\x06gameId\x18\x01 \x01(\x05\"#\n\x11LoginGameQueryRes\x12\x0e\n\x06gameId\x18\x01 \x01(\x05\"&\n\x12LogoutNotifyG2LY_N\x12\x10\n\x08logoutDB\x18\x01 \x01(\x08\"\x0f\n\rLogoutGameReq\"\x0f\n\rLogoutGameRes\"#\n\x10\x43hangeChannelReq\x12\x0f\n\x07\x65nterId\x18\x01 \x01(\x05\"\xaf\x01\n\nKickNotify\x12\x31\n\x06reason\x18\x01 \x01(\x0e\x32!.gate.KickNotify.KickNotifyReason\"n\n\x10KickNotifyReason\x12\x1a\n\x16KICKNOTIFY_REASON_NONE\x10\x00\x12\x1d\n\x19KICKNOTIFY_REASON_REPLACE\x10\x01\x12\x1f\n\x1bKICKNOTIFY_REASON_NOT_EXIST\x10\x02\x42\x1c\n\x17\x66rame.socket.gate.proto\xf8\x01\x01\x62\x06proto3')
)



_KICKNOTIFY_KICKNOTIFYREASON = _descriptor.EnumDescriptor(
  name='KickNotifyReason',
  full_name='gate.KickNotify.KickNotifyReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KICKNOTIFY_REASON_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KICKNOTIFY_REASON_REPLACE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KICKNOTIFY_REASON_NOT_EXIST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=481,
  serialized_end=591,
)
_sym_db.RegisterEnumDescriptor(_KICKNOTIFY_KICKNOTIFYREASON)


_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='gate.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='siteId', full_name='gate.LoginReq.siteId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='gate.LoginReq.userId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='gate.LoginReq.auth', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=82,
)


_LOGING2LY_R = _descriptor.Descriptor(
  name='LoginG2LY_R',
  full_name='gate.LoginG2LY_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=97,
)


_LOGINFAILURELY2G_S = _descriptor.Descriptor(
  name='LoginFailureLY2G_S',
  full_name='gate.LoginFailureLY2G_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=119,
)


_RECONNECTREQ = _descriptor.Descriptor(
  name='ReconnectReq',
  full_name='gate.ReconnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='siteId', full_name='gate.ReconnectReq.siteId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='gate.ReconnectReq.userId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enterId', full_name='gate.ReconnectReq.enterId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='gate.ReconnectReq.auth', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=198,
)


_RECONNECTRES = _descriptor.Descriptor(
  name='ReconnectRes',
  full_name='gate.ReconnectRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='gate.ReconnectRes.auth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=228,
)


_LOGINGAMEQUERYREQ = _descriptor.Descriptor(
  name='LoginGameQueryReq',
  full_name='gate.LoginGameQueryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='gate.LoginGameQueryReq.gameId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=265,
)


_LOGINGAMEQUERYRES = _descriptor.Descriptor(
  name='LoginGameQueryRes',
  full_name='gate.LoginGameQueryRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='gate.LoginGameQueryRes.gameId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=302,
)


_LOGOUTNOTIFYG2LY_N = _descriptor.Descriptor(
  name='LogoutNotifyG2LY_N',
  full_name='gate.LogoutNotifyG2LY_N',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logoutDB', full_name='gate.LogoutNotifyG2LY_N.logoutDB', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=342,
)


_LOGOUTGAMEREQ = _descriptor.Descriptor(
  name='LogoutGameReq',
  full_name='gate.LogoutGameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=359,
)


_LOGOUTGAMERES = _descriptor.Descriptor(
  name='LogoutGameRes',
  full_name='gate.LogoutGameRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=376,
)


_CHANGECHANNELREQ = _descriptor.Descriptor(
  name='ChangeChannelReq',
  full_name='gate.ChangeChannelReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enterId', full_name='gate.ChangeChannelReq.enterId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=413,
)


_KICKNOTIFY = _descriptor.Descriptor(
  name='KickNotify',
  full_name='gate.KickNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='gate.KickNotify.reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KICKNOTIFY_KICKNOTIFYREASON,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=591,
)

_KICKNOTIFY.fields_by_name['reason'].enum_type = _KICKNOTIFY_KICKNOTIFYREASON
_KICKNOTIFY_KICKNOTIFYREASON.containing_type = _KICKNOTIFY
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['LoginG2LY_R'] = _LOGING2LY_R
DESCRIPTOR.message_types_by_name['LoginFailureLY2G_S'] = _LOGINFAILURELY2G_S
DESCRIPTOR.message_types_by_name['ReconnectReq'] = _RECONNECTREQ
DESCRIPTOR.message_types_by_name['ReconnectRes'] = _RECONNECTRES
DESCRIPTOR.message_types_by_name['LoginGameQueryReq'] = _LOGINGAMEQUERYREQ
DESCRIPTOR.message_types_by_name['LoginGameQueryRes'] = _LOGINGAMEQUERYRES
DESCRIPTOR.message_types_by_name['LogoutNotifyG2LY_N'] = _LOGOUTNOTIFYG2LY_N
DESCRIPTOR.message_types_by_name['LogoutGameReq'] = _LOGOUTGAMEREQ
DESCRIPTOR.message_types_by_name['LogoutGameRes'] = _LOGOUTGAMERES
DESCRIPTOR.message_types_by_name['ChangeChannelReq'] = _CHANGECHANNELREQ
DESCRIPTOR.message_types_by_name['KickNotify'] = _KICKNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQ,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LoginReq)
  ))
_sym_db.RegisterMessage(LoginReq)

LoginG2LY_R = _reflection.GeneratedProtocolMessageType('LoginG2LY_R', (_message.Message,), dict(
  DESCRIPTOR = _LOGING2LY_R,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LoginG2LY_R)
  ))
_sym_db.RegisterMessage(LoginG2LY_R)

LoginFailureLY2G_S = _reflection.GeneratedProtocolMessageType('LoginFailureLY2G_S', (_message.Message,), dict(
  DESCRIPTOR = _LOGINFAILURELY2G_S,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LoginFailureLY2G_S)
  ))
_sym_db.RegisterMessage(LoginFailureLY2G_S)

ReconnectReq = _reflection.GeneratedProtocolMessageType('ReconnectReq', (_message.Message,), dict(
  DESCRIPTOR = _RECONNECTREQ,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.ReconnectReq)
  ))
_sym_db.RegisterMessage(ReconnectReq)

ReconnectRes = _reflection.GeneratedProtocolMessageType('ReconnectRes', (_message.Message,), dict(
  DESCRIPTOR = _RECONNECTRES,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.ReconnectRes)
  ))
_sym_db.RegisterMessage(ReconnectRes)

LoginGameQueryReq = _reflection.GeneratedProtocolMessageType('LoginGameQueryReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINGAMEQUERYREQ,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LoginGameQueryReq)
  ))
_sym_db.RegisterMessage(LoginGameQueryReq)

LoginGameQueryRes = _reflection.GeneratedProtocolMessageType('LoginGameQueryRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGINGAMEQUERYRES,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LoginGameQueryRes)
  ))
_sym_db.RegisterMessage(LoginGameQueryRes)

LogoutNotifyG2LY_N = _reflection.GeneratedProtocolMessageType('LogoutNotifyG2LY_N', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTNOTIFYG2LY_N,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LogoutNotifyG2LY_N)
  ))
_sym_db.RegisterMessage(LogoutNotifyG2LY_N)

LogoutGameReq = _reflection.GeneratedProtocolMessageType('LogoutGameReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTGAMEREQ,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LogoutGameReq)
  ))
_sym_db.RegisterMessage(LogoutGameReq)

LogoutGameRes = _reflection.GeneratedProtocolMessageType('LogoutGameRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTGAMERES,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.LogoutGameRes)
  ))
_sym_db.RegisterMessage(LogoutGameRes)

ChangeChannelReq = _reflection.GeneratedProtocolMessageType('ChangeChannelReq', (_message.Message,), dict(
  DESCRIPTOR = _CHANGECHANNELREQ,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.ChangeChannelReq)
  ))
_sym_db.RegisterMessage(ChangeChannelReq)

KickNotify = _reflection.GeneratedProtocolMessageType('KickNotify', (_message.Message,), dict(
  DESCRIPTOR = _KICKNOTIFY,
  __module__ = 'gate.login_pb2'
  # @@protoc_insertion_point(class_scope:gate.KickNotify)
  ))
_sym_db.RegisterMessage(KickNotify)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
