# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route/route.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import type_pb2 as common_dot_type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='route/route.proto',
  package='route',
  syntax='proto3',
  serialized_options=_b('\n\030frame.socket.route.proto\370\001\001'),
  serialized_pb=_b('\n\x11route/route.proto\x12\x05route\x1a\x11\x63ommon/type.proto\"\'\n\rRegisterA2R_R\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02no\x18\x02 \x01(\x05\"e\n\x12RegisterDebugA2R_R\x12\n\n\x02id\x18\x01 \x01(\x05\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.common.Server_Type\x12\x10\n\x08sub_type\x18\x03 \x01(\x05\x12\x0e\n\x06siteId\x18\x04 \x01(\x05\"\x0f\n\rRegisterR2A_SB\x1d\n\x18\x66rame.socket.route.proto\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[common_dot_type__pb2.DESCRIPTOR,])




_REGISTERA2R_R = _descriptor.Descriptor(
  name='RegisterA2R_R',
  full_name='route.RegisterA2R_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='route.RegisterA2R_R.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no', full_name='route.RegisterA2R_R.no', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=86,
)


_REGISTERDEBUGA2R_R = _descriptor.Descriptor(
  name='RegisterDebugA2R_R',
  full_name='route.RegisterDebugA2R_R',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='route.RegisterDebugA2R_R.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='route.RegisterDebugA2R_R.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='route.RegisterDebugA2R_R.sub_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='route.RegisterDebugA2R_R.siteId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=189,
)


_REGISTERR2A_S = _descriptor.Descriptor(
  name='RegisterR2A_S',
  full_name='route.RegisterR2A_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=206,
)

_REGISTERDEBUGA2R_R.fields_by_name['type'].enum_type = common_dot_type__pb2._SERVER_TYPE
DESCRIPTOR.message_types_by_name['RegisterA2R_R'] = _REGISTERA2R_R
DESCRIPTOR.message_types_by_name['RegisterDebugA2R_R'] = _REGISTERDEBUGA2R_R
DESCRIPTOR.message_types_by_name['RegisterR2A_S'] = _REGISTERR2A_S
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterA2R_R = _reflection.GeneratedProtocolMessageType('RegisterA2R_R', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERA2R_R,
  __module__ = 'route.route_pb2'
  # @@protoc_insertion_point(class_scope:route.RegisterA2R_R)
  ))
_sym_db.RegisterMessage(RegisterA2R_R)

RegisterDebugA2R_R = _reflection.GeneratedProtocolMessageType('RegisterDebugA2R_R', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERDEBUGA2R_R,
  __module__ = 'route.route_pb2'
  # @@protoc_insertion_point(class_scope:route.RegisterDebugA2R_R)
  ))
_sym_db.RegisterMessage(RegisterDebugA2R_R)

RegisterR2A_S = _reflection.GeneratedProtocolMessageType('RegisterR2A_S', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERR2A_S,
  __module__ = 'route.route_pb2'
  # @@protoc_insertion_point(class_scope:route.RegisterR2A_S)
  ))
_sym_db.RegisterMessage(RegisterR2A_S)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
