# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/error.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n\031frame.socket.common.proto\370\001\001'),
  serialized_pb=_b('\n\x12\x63ommon/error.proto\x12\x06\x63ommon\"3\n\x08\x45rrorRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\x1f\n\x08\x44\x45\x42UGREQ\x12\x13\n\x0b\x64\x65\x62ugString\x18\x01 \x01(\tB\x1e\n\x19\x66rame.socket.common.proto\xf8\x01\x01\x62\x06proto3')
)




_ERRORRES = _descriptor.Descriptor(
  name='ErrorRes',
  full_name='common.ErrorRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='common.ErrorRes.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.ErrorRes.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.ErrorRes.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_DEBUGREQ = _descriptor.Descriptor(
  name='DEBUGREQ',
  full_name='common.DEBUGREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='debugString', full_name='common.DEBUGREQ.debugString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['ErrorRes'] = _ERRORRES
DESCRIPTOR.message_types_by_name['DEBUGREQ'] = _DEBUGREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorRes = _reflection.GeneratedProtocolMessageType('ErrorRes', (_message.Message,), dict(
  DESCRIPTOR = _ERRORRES,
  __module__ = 'common.error_pb2'
  # @@protoc_insertion_point(class_scope:common.ErrorRes)
  ))
_sym_db.RegisterMessage(ErrorRes)

DEBUGREQ = _reflection.GeneratedProtocolMessageType('DEBUGREQ', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGREQ,
  __module__ = 'common.error_pb2'
  # @@protoc_insertion_point(class_scope:common.DEBUGREQ)
  ))
_sym_db.RegisterMessage(DEBUGREQ)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
