# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/gameHistory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/gameHistory.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x63ommon/gameHistory.proto\"\xa9\x01\n\x0bResHistorys\x12\x11\n\tpageIndex\x18\x01 \x01(\x05\x12\x0f\n\x07pageMax\x18\x02 \x01(\x05\x12\'\n\x05games\x18\x03 \x03(\x0b\x32\x18.ResHistorys.gameHistory\x1aM\n\x0bgameHistory\x12\x0f\n\x07\x65ndTime\x18\x01 \x01(\x06\x12\x0b\n\x03win\x18\x02 \x01(\x03\x12\x10\n\x08roomName\x18\x03 \x01(\t\x12\x0e\n\x06gameId\x18\x04 \x01(\t\"2\n\x0bReqHistorys\x12\x10\n\x08pageSize\x18\x01 \x01(\x05\x12\x11\n\tpageIndex\x18\x02 \x01(\x05\x62\x06proto3')
)




_RESHISTORYS_GAMEHISTORY = _descriptor.Descriptor(
  name='gameHistory',
  full_name='ResHistorys.gameHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endTime', full_name='ResHistorys.gameHistory.endTime', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='win', full_name='ResHistorys.gameHistory.win', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roomName', full_name='ResHistorys.gameHistory.roomName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='ResHistorys.gameHistory.gameId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=198,
)

_RESHISTORYS = _descriptor.Descriptor(
  name='ResHistorys',
  full_name='ResHistorys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageIndex', full_name='ResHistorys.pageIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageMax', full_name='ResHistorys.pageMax', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='games', full_name='ResHistorys.games', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESHISTORYS_GAMEHISTORY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=198,
)


_REQHISTORYS = _descriptor.Descriptor(
  name='ReqHistorys',
  full_name='ReqHistorys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ReqHistorys.pageSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageIndex', full_name='ReqHistorys.pageIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=250,
)

_RESHISTORYS_GAMEHISTORY.containing_type = _RESHISTORYS
_RESHISTORYS.fields_by_name['games'].message_type = _RESHISTORYS_GAMEHISTORY
DESCRIPTOR.message_types_by_name['ResHistorys'] = _RESHISTORYS
DESCRIPTOR.message_types_by_name['ReqHistorys'] = _REQHISTORYS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResHistorys = _reflection.GeneratedProtocolMessageType('ResHistorys', (_message.Message,), dict(

  gameHistory = _reflection.GeneratedProtocolMessageType('gameHistory', (_message.Message,), dict(
    DESCRIPTOR = _RESHISTORYS_GAMEHISTORY,
    __module__ = 'common.gameHistory_pb2'
    # @@protoc_insertion_point(class_scope:ResHistorys.gameHistory)
    ))
  ,
  DESCRIPTOR = _RESHISTORYS,
  __module__ = 'common.gameHistory_pb2'
  # @@protoc_insertion_point(class_scope:ResHistorys)
  ))
_sym_db.RegisterMessage(ResHistorys)
_sym_db.RegisterMessage(ResHistorys.gameHistory)

ReqHistorys = _reflection.GeneratedProtocolMessageType('ReqHistorys', (_message.Message,), dict(
  DESCRIPTOR = _REQHISTORYS,
  __module__ = 'common.gameHistory_pb2'
  # @@protoc_insertion_point(class_scope:ReqHistorys)
  ))
_sym_db.RegisterMessage(ReqHistorys)


# @@protoc_insertion_point(module_scope)
