# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/register.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/register.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n\031frame.socket.common.proto\370\001\001'),
  serialized_pb=_b('\n\x15\x63ommon/register.proto\x12\x06\x63ommonB\x1e\n\x19\x66rame.socket.common.proto\xf8\x01\x01\x62\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
