# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/type.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n\031frame.socket.common.proto\370\001\001'),
  serialized_pb=_b('\n\x11\x63ommon/type.proto\x12\x06\x63ommon*\xd9\x02\n\x0bServer_Type\x12\x14\n\x10SERVER_TYPE_GATE\x10\x00\x12\x15\n\x11SERVER_TYPE_ROUTE\x10\x01\x12\x14\n\x10SERVER_TYPE_GAME\x10\x02\x12\x16\n\x12SERVER_TYPE_RECORD\x10\x03\x12\x18\n\x14SERVER_TYPE_DATABASE\x10\x04\x12\x16\n\x12SERVER_TYPE_GLOBAL\x10\x05\x12\x15\n\x11SERVER_TYPE_LOBBY\x10\x06\x12\x15\n\x11SERVER_TYPE_LOGIN\x10\x07\x12\x17\n\x13SERVER_TYPE_ACCOUNT\x10\x08\x12\x18\n\x14SERVER_TYPE_ACTIVITY\x10\t\x12\x14\n\x10SERVER_TYPE_FILE\x10\n\x12\x17\n\x13SERVER_TYPE_CONTROL\x10\x0b\x12\x15\n\x11SERVER_TYPE_AGENT\x10\x0c\x12\x16\n\x12SERVER_TYPE_BACKUP\x10\rB\x1e\n\x19\x66rame.socket.common.proto\xf8\x01\x01\x62\x06proto3')
)

_SERVER_TYPE = _descriptor.EnumDescriptor(
  name='Server_Type',
  full_name='common.Server_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_GATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_ROUTE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_GAME', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_RECORD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_DATABASE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_GLOBAL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_LOBBY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_LOGIN', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_ACCOUNT', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_ACTIVITY', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_FILE', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_CONTROL', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_AGENT', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_TYPE_BACKUP', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=30,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_SERVER_TYPE)

Server_Type = enum_type_wrapper.EnumTypeWrapper(_SERVER_TYPE)
SERVER_TYPE_GATE = 0
SERVER_TYPE_ROUTE = 1
SERVER_TYPE_GAME = 2
SERVER_TYPE_RECORD = 3
SERVER_TYPE_DATABASE = 4
SERVER_TYPE_GLOBAL = 5
SERVER_TYPE_LOBBY = 6
SERVER_TYPE_LOGIN = 7
SERVER_TYPE_ACCOUNT = 8
SERVER_TYPE_ACTIVITY = 9
SERVER_TYPE_FILE = 10
SERVER_TYPE_CONTROL = 11
SERVER_TYPE_AGENT = 12
SERVER_TYPE_BACKUP = 13


DESCRIPTOR.enum_types_by_name['Server_Type'] = _SERVER_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
